# Generated by Django 4.2.7 on 2023-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todolist_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
